version: '2'
services:
    river-mysql:
        container_name: river-mysql
        image: mysql:5.7.14
        # volumes:
        #     - ~/volumes/jhipster/river/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=river
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
